### ISSUE TITLE
[Internal] Implement CRM internal API

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#112]
# Overview

Some of Connie's core functionality (e.g. caller ID, shared agent-client activity) relies on the Connie client having a CRM to fetch data on a CBO's clients. As such, we should build a clear developer-oriented API that allows this other functionality to be implemented in a consistent way.

# Acceptance Criteria

- There is a Connie-wide client-side API to fetch client contact data from a CRM
- The client can retrieve a record using a particular phone number

# Tasks

- [ ] Implement Airtable [token-based authentication](https://airtable.com/developers/web/guides/personal-access-tokens)
- [ ] Implement custom API layer for Airtable API
- [ ] Ensure Airtable API is initialized in Next.js client on page load

# Additional Info

The data types that we must support are:
- Strings
- Numbers
- Dates
- Emails

Any lists of objects should be represented in the API as raw strings for the time being.

To be forward facing and provide , we should adopt an internal API that looks something like this:

```ts
// Data type that encapsulates 
type CRMEntry = { [key: string]: number };

interface CRMTable {
   getRowById(id: string): CRMEntry | null;
   getClientByPhone(phoneNumber: string): CRMEntry | null;
}

interface ConnieCRMProvider {
  getTable(id: string): CRMTable;
  getDefaultTable(): CRMTable;
}
```

Example usage being:
```tsx
class AirtableCRMProvider implements ConnieCRMProvider {
  constructor() {
    // ...
  }

  getTable(id: string): CRMTable {
    // ...
  }
  getDefaultTable(): CRMTable() {
    // ..
  }
}

export default async function DemoPage() {
  const crm = new AirtableCRMProvider();
  // Assuming there's a React context that exposes data from
  return (
    <CRMProviderContext.Provider crm={crm}>
      <DemoPanel />
    </CRMProviderContext.Provider>
  );
}
```
```ts
"use client";

function DemoPanel() {
  const {getDefaultTable} = useAirtableCRMProvider();
  const clientPhoneNumber = "555-555-5555";
  const clientData = getDefaultTable().getClientByPhone(clientPhoneNumber);
  return (
    <div>
    <div>Name: {clientData.name ?? "Name unknown"}</div>
    <div>Name: {clientData.email ?? "Email unknown"}</div>
    <div>Name: {clientData.address ?? "Address unknown"}</div>
    </div>
  );
}
```

**Comment by lohpaul9** [comment]
Completed with PR #114
