### ISSUE TITLE
[Internal] Refactor Prototype 1 code

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#72]
# Overview

The existing codebase was originally built using the pages router for Next.js, but for this stage of the project, we want to focus on longevity.

Additionally, we need to rebuild this in a way that supports easy containerization for deployment on potentially multi-tenant workflows.

# Acceptance Criteria

- [x] The Connie-RTC repo consists of a Next.js app using the Next.js app directory
- [x] All existing issue and pull request templates in the `.github` folder are preserved and accessible in the refactored code
- [x] There is an updated README containing information on how anyone in the team can get started developing Connie

# Tasks

- [ ] Create a new Next.js app using the default settings
- [ ] Make a copy of the existing Phase I code
- [ ] Clone a new copy of the Connie-RTC repo, preserving Git history
- [ ] Delete all the code in the new copy of the project
- [ ] Copy the new Next.js app code to the new project
- [ ] Add any desired code from the old project to the new project
- [ ] Commit and push the changes in the new project to a new short-lived feature branch

**Comment by WillieCubed** [comment]
To clarify the tasks: I was missing a step to actually move existing code to the new version of the repository. Also, we're still using this GitHub repo, just preserving the Git history. To start, just do the minimum needed to meet the acceptance criteria. @israelhhh2 will have to make a final determination about which old `pages` routes should be migrated to new app router-based routes.

**Comment by WillieCubed** [comment]
Closed by #82
