### ISSUE TITLE
Basic Agent Auth

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#74]
**As a CBO agent, I should be able to sign into Connie using credentials provided by so I can access my dashboard.**

# Acceptance Criteria

- [ ] A CBO agent can use a web browser to sign into Connie using credentials provided to them or created by their CBO
- [ ] A CBO agent is redirected to the Connie dashboard upon successful sign-in
- [ ] A CBO agent is presented with an error message if they input incorrect credentials in the sign-in page
- [ ] A CBO agent is redirected to the Connie landing page upon sign-out

# Tasks

- [ ] Implement sign-in flow using [Okta Customer Identity Cloud](https://www.okta.com/customer-identity/)

# Additional Info

The assignees of this issue should work with @chrisberno to learn more about the existing and desired sign-in flow with Okta.

**Comment by chrisberno** [comment]
**Note 1:** Assignees of this task will need admin / developer level credentials in the ASA OKTA account to be able to 1) set up the SAML / OAUTH2 connections and add other DFG team members. @WillieCubed and @israelhhh2 are already OKTA admins and I will go ahead add @AlexanderTsarapkine & @minfeishen2024 <= Be on the lookout from an invite from OKtA and let me know if anyone has problems logging in. 

Note 2: @cam-obrien successfully lead / implemented user auth & permissions for prototype v1 so perhaps check out the V1 repo to fast track. I'm 99% sure he used [Auth.js ](https://authjs.dev/) which is well documented with good client and server side set up instructions. <= Hope that helps a bit. 

Link To OKTA Customer Identity Cloud: https://www.okta.com/customer-identity/
Link To Twilio SSO Setup w/ OKTA: https://www.twilio.com/docs/iam/single-sign-on/configuring-okta-with-twilio-sso

LMK if you want to set up a call to run through any of this.  🤓 cjb

**Comment by AlexanderTsarapkine** [comment]
Small Update regarding the following link:
         Link To Twilio SSO Setup w/ OKTA: https://www.twilio.com/docs/iam/single-sign-on/configuring-okta-with-twilio-sso
         
This uses IAM which after discussing with Chris, is not what we want

**Comment by AlexanderTsarapkine** [comment]
Note 2:
Cant use next-auth for SAML, implementing authentication with passport.js. This means we cant really use any of the previous cohorts work for authentication.

**Comment by AlexanderTsarapkine** [comment]
After discussing at length with Chris, we have changed back to OIDC protocol due to lack of SAML support and no real benefit.
