### ISSUE TITLE
App Navigation

### ISSUE THREAD

**Issue by israelhhh2** [ConnieML/Connie-RTC#75]
**As a Connie user, I should be able to easily navigate the agent portal and access all of Connie's features so I can efficiently get work done.**

# Acceptance Criteria

- [ ] A CBO agent can access their main dashboard from the app's top-level navigation
- [ ] A CBO program manager can access analytics from the app's top-level navigation
- [ ] A CBO agent can access an overview of their notifications from any screen in the app
- [ ] A CBO can access account settings from globally-accessible navigation
- [ ] A CBO can log out from globally-accessible navigation

# Tasks

- [ ] come up with a final UI for the portal. 
- [x] #77
- [x] Implement mockups in code using Next.js

# Additional Info

As of right now we do not have a Design Manager. @WillieCubed will be filling in that role for the meantime so work with him to work on the UI/UX of the portal.

Any mockups developed should be based off the [UI research](https://www.notion.so/developforgood/UI-UX-Research-e74d1675e5be44daa739fea10fe34c4a) that was done.

**Comment by michelleshx** [comment]
#83
