### ISSUE TITLE
Agent Availability Status

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#76]
**As a CBO agent, I should be able to change my availability status so I can choose when I receive notifications for incoming communications.**

# Acceptance Criteria

- [ ] A CBO agent can mark their availability status as available and unavailable
- [ ] If a CBO agent's status is unavailable, they must not receive any notifications, including calls
- [ ] If a CBO agent's status is available, they should be able to receive incoming notifications, including calls

# Tasks

- [x] Create a component that allows an agent to update their availability
- [ ] Prevent notifications from going to unavailable agents
