### ISSUE TITLE
[Internal] Create app skeleton UI

### ISSUE THREAD

**Issue by israelhhh2** [ConnieML/Connie-RTC#77]
As a CBO agent, I should find the Connie interface aesthetically pleasing while also experiencing ease of use.

# Acceptance Criteria
- [ ] Connie's main layout elements should be correctly positioned 
- [ ] A CBO should be able to see the Connie's logo and name for brand recognition
- [ ] Responsive Design 
- [ ] UI consistency
- [ ] Colors should align with ASA identity. 

# Tasks
- [ ] Using your [UI research](https://www.notion.so/developforgood/UI-UX-Research-e74d1675e5be44daa739fea10fe34c4a) come up with a final UI for the portal. 
- [ ] Create a mockup in figma 

# Additional Info
As of right now we do not have a dedicated Design Manager. @WillieCubed will be filling in that role in the mean time so work with him in order to create the final UI.

**Comment by WillieCubed** [comment]
Current TODOs are:

- [x] Create modal dialog to initiate calls
- [x] Create app-wide side navigation bar
- [ ] Create outlines for:
  - [ ] User home page
  - [ ] BIlling and usage analytics page
  - [ ] Account settings page
- [x] Create UI for viewing user notifications
