### ISSUE TITLE
[Internal] Set up a Twilio TaskRouter Workspace

### ISSUE THREAD

**Issue by israelhhh2** [ConnieML/Connie-RTC#85]
# Overview
Twilio's TaskRouter is a skills-based routing system that provides the heart of a contact center that we should control from our code. We should be able to match tasks to workers while maintaining escalation and fallback rules. 

# Acceptance Criteria

- [ ] Our TaskRouter Workspace should be setup
- [ ] We should have a couple of workers setup for testing purposes

# Tasks

- [ ] Create a TaskRouter workspace
- [ ] Add and Configure Workers
- [ ] Add and Configure TaskQueues
- [ ] Add and Configure a Workflow
- [ ] Understand Activities

# Additional Info

- Read [here](https://www.twilio.com/docs/taskrouter/how-taskrouter-works) on how taskrouter works
- Use cohort 1 handover [docs](https://www.notion.so/developforgood/Project-Setup-6a0376b2cdc2434093843b4d2fa27dc9#c5799f9b06ea43c6b0037200bcf2ef79) as a reference
- Some taskrouter [docs](https://www.twilio.com/docs/taskrouter/quickstart/csharp/setup) that might be helpful

**Comment by WillieCubed** [comment]
@ShohruzE We've given you access to the Twilio console. Let us know if you need any more assistance.

**Comment by minfeishen2024** [comment]
Taskrouter Workspace Configured on Twilio Console
