### ISSUE TITLE
Past Notifications

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#94]
**As an agent, I should be able to see all past notifications so I can review anything I missed.**

# Acceptance Criteria

- CBO agent is able to view all notifications they have been sent before

# Tasks

- [ ] Create an interface/functions to store and retrieve notification events
- [ ] Store notifications in a key-value store
- [ ] Implement notifications pop-up dialog that's accessible from the top app bar

# Additional Info

For now, notifications should be in the form of missed calls and text messages that have not been explicitly resolved. Every notification should keep track of when it was originally created and have a flag that keeps track of whether it was resolved.

Final mockups TBD
