### ISSUE TITLE
Agent-Client Shared Activity

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#95]
**As an agent, I should be able to see all past activity I have had with a client so I can have better context when I communicate with them moving forward.**

# Acceptance Criteria

- CBO agent can see all phone calls initiated and received from a client contact
- CBO agent can see all text messages sent and received from a client contact
- CBO agent can see all notes associated with a client contact

# Tasks

- [ ] Create a data model for a shared activity item
- [ ] Create a component to show a stream of shared client/agent activity
- [ ] Embed component in main agent/client contact page

# Additional Info

The UI for this is still a WIP.
