### ISSUE TITLE
Client Search

### ISSUE THREAD

**Issue by WillieCubed** [ConnieML/Connie-RTC#96]
**As an agent, I should be able to search all clients known by my CBO so I can initiate or continue contact with them.**

# Acceptance Criteria

- CBO agent can use a search box that populates with clients to find a client to initiate a call
- CBO agent can search contacts by phone number
- CBO agent can search contacts by name

# Tasks

- [ ] Implement search box component
- [ ] Retrieve results from CBO's contact database and match contacts by phone number
- [ ] Add search box to calling UI

# Additional Info

Mockups available [here](https://www.figma.com/file/g7tCrZAvJdxQBAJpc6GScW/American-Society-On-Aging?type=design&node-id=1138%3A25827&mode=design&t=s7ibwEUar952b0NU-1).

**Comment by WillieCubed** [comment]
Currently waiting on API for CRM (#112).

**Comment by WillieCubed** [comment]
To clarify from a team meeting today, this functionality will be accessible from a dedicated client list page. Mockup [here](https://www.figma.com/file/g7tCrZAvJdxQBAJpc6GScW/American-Society-On-Aging?type=design&node-id=1138%3A25827&mode=design&t=s7ibwEUar952b0NU-1). Note that:

- The returned results should update as the user updates their search query
- The search should search by all supported columns if possible (i.e. search by client name, by phone number, etc.)
